### PR TITLE
Build docker images for linux/arm64

### PR DESCRIPTION
**Pull request by gregorycollins**
Verified that the release workflow works on our fork.

### CODE REVIEW

**Comment by stvnksslr** [comment]
lgtm 👍

**Comment by jmriebold** [comment]
Thanks @gregorycollins!

**Comment by gregorycollins** [comment]
~@jmriebold I will probably have a follow-up: go SDK v1 doesn't work with the new EKS Pod Identity feature, we are getting the same error that's described here: https://github.com/aws-controllers-k8s/community/issues/1953~

Edit: You're already on v2, clearly I need to track this down

**Comment by gregorycollins** [comment]
P.S. and thank you for writing a useful program we've been using 👍

**Comment by stvnksslr** [comment]
Its been on my todo list to upgrade the sdk to the latest will try to get out a release soon for it should be a simple upgrade.

**Comment by stvnksslr** [comment]
#19 work or additional requirements can be tracked here

**Comment by jmriebold** [comment]
@gregorycollins what's the error you're seeing? Is it possible that it'd be fixed by #19?

Edit: oh I assume it's the error described in that GH issue.

**Comment by jmriebold** [comment]
Just cut a release on the off chance that that fixes your issue. The Pod Identity stuff is pretty new if I'm not mistaken, so it's probably worth a shot.

**Comment by gregorycollins** [comment]
We will test it asap and I will get back to you!

**Comment by gregorycollins** [comment]
@jmriebold confirmed that with the updated SDK the pod identity stuff now seems to be working, thank you. 🙏

**Comment by jmriebold** [comment]
Woohoo! Glad to hear it.

**Pull request merged**
